@startuml AntiBruteforceComponents
skinparam componentStyle rectangle
skinparam WrapWidth 180
skinparam DefaultFontName Monospace

package "Anti‑Bruteforce Service" {
  [Transport: gRPC/HTTP]
  [Application Service]
  [Core: RateLimiter]
  [SubnetList Matcher: In‑Memory]


  [Transport: gRPC/HTTP] --> [Application Service] : CheckAttempt(), ResetBuckets(), ManageLists()
  [Application Service] --> [Core: RateLimiter] : allow(login, password, ip)
  [Application Service] -->  [SubnetList Matcher: In‑Memory] : check IP in black/white
  [Application Service] --> [SubnetList Store] : manage IP in black/white


  [Core: RateLimiter] --> [Bucket Store]

  [SubnetList Matcher: In‑Memory] <-down- [Sub/Pub Listener] : update lists


}

package "Infra" {
  [PostgreSQL : lists]
  [Redis : buckets]
  [Redis Pub/Sub : lists updates]
  [Config]
}

[Bucket Store] --> [Redis : buckets]
[SubnetList Store] --> [PostgreSQL : lists]
[SubnetList Store] --> [Redis Pub/Sub : lists updates] : publish updates
[Sub/Pub Listener] <-- [Redis Pub/Sub : lists updates]
[Application Service] --> [Config]
[SubnetList Matcher: In‑Memory] --> [PostgreSQL : lists] 

package "External Clients" {
  [Auth Service] as Client
  [Admin CLI]
}

Client --> [Transport: gRPC/HTTP] : server‑to‑server API
[Admin CLI] --> [Transport: gRPC/HTTP] : admin methods

@enduml