// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: anti_bruteforce.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AntiBruteforce_CheckAttempt_FullMethodName        = "/abf.v1.AntiBruteforce/CheckAttempt"
	AntiBruteforce_ResetBucket_FullMethodName         = "/abf.v1.AntiBruteforce/ResetBucket"
	AntiBruteforce_AddToWhitelist_FullMethodName      = "/abf.v1.AntiBruteforce/AddToWhitelist"
	AntiBruteforce_RemoveFromWhitelist_FullMethodName = "/abf.v1.AntiBruteforce/RemoveFromWhitelist"
	AntiBruteforce_AddToBlacklist_FullMethodName      = "/abf.v1.AntiBruteforce/AddToBlacklist"
	AntiBruteforce_RemoveFromBlacklist_FullMethodName = "/abf.v1.AntiBruteforce/RemoveFromBlacklist"
)

// AntiBruteforceClient is the client API for AntiBruteforce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Реализация сервиса защиты от брутфорс атак.
// В соответствии с техзаданием реализованы методы проверки попытки входа,
// сброса счетчиков и управления белым и черным списками CIDR.
type AntiBruteforceClient interface {
	CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptResponse, error)
	ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*ResetBucketResponse, error)
	AddToWhitelist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error)
	RemoveFromWhitelist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error)
	AddToBlacklist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error)
	RemoveFromBlacklist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error)
}

type antiBruteforceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiBruteforceClient(cc grpc.ClientConnInterface) AntiBruteforceClient {
	return &antiBruteforceClient{cc}
}

func (c *antiBruteforceClient) CheckAttempt(ctx context.Context, in *CheckAttemptRequest, opts ...grpc.CallOption) (*CheckAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAttemptResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_CheckAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) ResetBucket(ctx context.Context, in *ResetBucketRequest, opts ...grpc.CallOption) (*ResetBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetBucketResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_ResetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToWhitelist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageCIDRResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_AddToWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) RemoveFromWhitelist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageCIDRResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_RemoveFromWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) AddToBlacklist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageCIDRResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_AddToBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteforceClient) RemoveFromBlacklist(ctx context.Context, in *ManageCIDRRequest, opts ...grpc.CallOption) (*ManageCIDRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManageCIDRResponse)
	err := c.cc.Invoke(ctx, AntiBruteforce_RemoveFromBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteforceServer is the server API for AntiBruteforce service.
// All implementations must embed UnimplementedAntiBruteforceServer
// for forward compatibility.
//
// Реализация сервиса защиты от брутфорс атак.
// В соответствии с техзаданием реализованы методы проверки попытки входа,
// сброса счетчиков и управления белым и черным списками CIDR.
type AntiBruteforceServer interface {
	CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptResponse, error)
	ResetBucket(context.Context, *ResetBucketRequest) (*ResetBucketResponse, error)
	AddToWhitelist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error)
	RemoveFromWhitelist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error)
	AddToBlacklist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error)
	RemoveFromBlacklist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error)
	mustEmbedUnimplementedAntiBruteforceServer()
}

// UnimplementedAntiBruteforceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAntiBruteforceServer struct{}

func (UnimplementedAntiBruteforceServer) CheckAttempt(context.Context, *CheckAttemptRequest) (*CheckAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAttempt not implemented")
}
func (UnimplementedAntiBruteforceServer) ResetBucket(context.Context, *ResetBucketRequest) (*ResetBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetBucket not implemented")
}
func (UnimplementedAntiBruteforceServer) AddToWhitelist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhitelist not implemented")
}
func (UnimplementedAntiBruteforceServer) RemoveFromWhitelist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhitelist not implemented")
}
func (UnimplementedAntiBruteforceServer) AddToBlacklist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlacklist not implemented")
}
func (UnimplementedAntiBruteforceServer) RemoveFromBlacklist(context.Context, *ManageCIDRRequest) (*ManageCIDRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlacklist not implemented")
}
func (UnimplementedAntiBruteforceServer) mustEmbedUnimplementedAntiBruteforceServer() {}
func (UnimplementedAntiBruteforceServer) testEmbeddedByValue()                        {}

// UnsafeAntiBruteforceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiBruteforceServer will
// result in compilation errors.
type UnsafeAntiBruteforceServer interface {
	mustEmbedUnimplementedAntiBruteforceServer()
}

func RegisterAntiBruteforceServer(s grpc.ServiceRegistrar, srv AntiBruteforceServer) {
	// If the following call pancis, it indicates UnimplementedAntiBruteforceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AntiBruteforce_ServiceDesc, srv)
}

func _AntiBruteforce_CheckAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).CheckAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_CheckAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).CheckAttempt(ctx, req.(*CheckAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_ResetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).ResetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_ResetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).ResetBucket(ctx, req.(*ResetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageCIDRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_AddToWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToWhitelist(ctx, req.(*ManageCIDRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_RemoveFromWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageCIDRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).RemoveFromWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_RemoveFromWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).RemoveFromWhitelist(ctx, req.(*ManageCIDRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_AddToBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageCIDRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).AddToBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_AddToBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).AddToBlacklist(ctx, req.(*ManageCIDRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteforce_RemoveFromBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageCIDRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteforceServer).RemoveFromBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteforce_RemoveFromBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteforceServer).RemoveFromBlacklist(ctx, req.(*ManageCIDRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiBruteforce_ServiceDesc is the grpc.ServiceDesc for AntiBruteforce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiBruteforce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abf.v1.AntiBruteforce",
	HandlerType: (*AntiBruteforceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAttempt",
			Handler:    _AntiBruteforce_CheckAttempt_Handler,
		},
		{
			MethodName: "ResetBucket",
			Handler:    _AntiBruteforce_ResetBucket_Handler,
		},
		{
			MethodName: "AddToWhitelist",
			Handler:    _AntiBruteforce_AddToWhitelist_Handler,
		},
		{
			MethodName: "RemoveFromWhitelist",
			Handler:    _AntiBruteforce_RemoveFromWhitelist_Handler,
		},
		{
			MethodName: "AddToBlacklist",
			Handler:    _AntiBruteforce_AddToBlacklist_Handler,
		},
		{
			MethodName: "RemoveFromBlacklist",
			Handler:    _AntiBruteforce_RemoveFromBlacklist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anti_bruteforce.proto",
}
