// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: anti_bruteforce.proto

package pbv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAttemptRequest) Reset() {
	*x = CheckAttemptRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptRequest) ProtoMessage() {}

func (x *CheckAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptRequest.ProtoReflect.Descriptor instead.
func (*CheckAttemptRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAttemptRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CheckAttemptRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CheckAttemptRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CheckAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAttemptResponse) Reset() {
	*x = CheckAttemptResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAttemptResponse) ProtoMessage() {}

func (x *CheckAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAttemptResponse.ProtoReflect.Descriptor instead.
func (*CheckAttemptResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAttemptResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ResetBucketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{2}
}

func (x *ResetBucketRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ResetBucketRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetBucketRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ResetBucketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetBucketResponse) Reset() {
	*x = ResetBucketResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketResponse) ProtoMessage() {}

func (x *ResetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketResponse.ProtoReflect.Descriptor instead.
func (*ResetBucketResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{3}
}

type ManageCIDRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCIDRRequest) Reset() {
	*x = ManageCIDRRequest{}
	mi := &file_anti_bruteforce_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCIDRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCIDRRequest) ProtoMessage() {}

func (x *ManageCIDRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCIDRRequest.ProtoReflect.Descriptor instead.
func (*ManageCIDRRequest) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{4}
}

func (x *ManageCIDRRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type ManageCIDRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageCIDRResponse) Reset() {
	*x = ManageCIDRResponse{}
	mi := &file_anti_bruteforce_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageCIDRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageCIDRResponse) ProtoMessage() {}

func (x *ManageCIDRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anti_bruteforce_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageCIDRResponse.ProtoReflect.Descriptor instead.
func (*ManageCIDRResponse) Descriptor() ([]byte, []int) {
	return file_anti_bruteforce_proto_rawDescGZIP(), []int{5}
}

var File_anti_bruteforce_proto protoreflect.FileDescriptor

const file_anti_bruteforce_proto_rawDesc = "" +
	"\n" +
	"\x15anti_bruteforce.proto\x12\x06abf.v1\"W\n" +
	"\x13CheckAttemptRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"&\n" +
	"\x14CheckAttemptResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"V\n" +
	"\x12ResetBucketRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\"\x15\n" +
	"\x13ResetBucketResponse\"'\n" +
	"\x11ManageCIDRRequest\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"\x14\n" +
	"\x12ManageCIDRResponse2\xd1\x03\n" +
	"\x0eAntiBruteforce\x12I\n" +
	"\fCheckAttempt\x12\x1b.abf.v1.CheckAttemptRequest\x1a\x1c.abf.v1.CheckAttemptResponse\x12F\n" +
	"\vResetBucket\x12\x1a.abf.v1.ResetBucketRequest\x1a\x1b.abf.v1.ResetBucketResponse\x12G\n" +
	"\x0eAddToWhitelist\x12\x19.abf.v1.ManageCIDRRequest\x1a\x1a.abf.v1.ManageCIDRResponse\x12L\n" +
	"\x13RemoveFromWhitelist\x12\x19.abf.v1.ManageCIDRRequest\x1a\x1a.abf.v1.ManageCIDRResponse\x12G\n" +
	"\x0eAddToBlacklist\x12\x19.abf.v1.ManageCIDRRequest\x1a\x1a.abf.v1.ManageCIDRResponse\x12L\n" +
	"\x13RemoveFromBlacklist\x12\x19.abf.v1.ManageCIDRRequest\x1a\x1a.abf.v1.ManageCIDRResponseBWZUgithub.com/Alexandr-Snisarenko/Otus-Anti-Bruteforce/api/proto/anti_bruteforce/v1;pbv1b\x06proto3"

var (
	file_anti_bruteforce_proto_rawDescOnce sync.Once
	file_anti_bruteforce_proto_rawDescData []byte
)

func file_anti_bruteforce_proto_rawDescGZIP() []byte {
	file_anti_bruteforce_proto_rawDescOnce.Do(func() {
		file_anti_bruteforce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anti_bruteforce_proto_rawDesc), len(file_anti_bruteforce_proto_rawDesc)))
	})
	return file_anti_bruteforce_proto_rawDescData
}

var file_anti_bruteforce_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_anti_bruteforce_proto_goTypes = []any{
	(*CheckAttemptRequest)(nil),  // 0: abf.v1.CheckAttemptRequest
	(*CheckAttemptResponse)(nil), // 1: abf.v1.CheckAttemptResponse
	(*ResetBucketRequest)(nil),   // 2: abf.v1.ResetBucketRequest
	(*ResetBucketResponse)(nil),  // 3: abf.v1.ResetBucketResponse
	(*ManageCIDRRequest)(nil),    // 4: abf.v1.ManageCIDRRequest
	(*ManageCIDRResponse)(nil),   // 5: abf.v1.ManageCIDRResponse
}
var file_anti_bruteforce_proto_depIdxs = []int32{
	0, // 0: abf.v1.AntiBruteforce.CheckAttempt:input_type -> abf.v1.CheckAttemptRequest
	2, // 1: abf.v1.AntiBruteforce.ResetBucket:input_type -> abf.v1.ResetBucketRequest
	4, // 2: abf.v1.AntiBruteforce.AddToWhitelist:input_type -> abf.v1.ManageCIDRRequest
	4, // 3: abf.v1.AntiBruteforce.RemoveFromWhitelist:input_type -> abf.v1.ManageCIDRRequest
	4, // 4: abf.v1.AntiBruteforce.AddToBlacklist:input_type -> abf.v1.ManageCIDRRequest
	4, // 5: abf.v1.AntiBruteforce.RemoveFromBlacklist:input_type -> abf.v1.ManageCIDRRequest
	1, // 6: abf.v1.AntiBruteforce.CheckAttempt:output_type -> abf.v1.CheckAttemptResponse
	3, // 7: abf.v1.AntiBruteforce.ResetBucket:output_type -> abf.v1.ResetBucketResponse
	5, // 8: abf.v1.AntiBruteforce.AddToWhitelist:output_type -> abf.v1.ManageCIDRResponse
	5, // 9: abf.v1.AntiBruteforce.RemoveFromWhitelist:output_type -> abf.v1.ManageCIDRResponse
	5, // 10: abf.v1.AntiBruteforce.AddToBlacklist:output_type -> abf.v1.ManageCIDRResponse
	5, // 11: abf.v1.AntiBruteforce.RemoveFromBlacklist:output_type -> abf.v1.ManageCIDRResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_anti_bruteforce_proto_init() }
func file_anti_bruteforce_proto_init() {
	if File_anti_bruteforce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anti_bruteforce_proto_rawDesc), len(file_anti_bruteforce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anti_bruteforce_proto_goTypes,
		DependencyIndexes: file_anti_bruteforce_proto_depIdxs,
		MessageInfos:      file_anti_bruteforce_proto_msgTypes,
	}.Build()
	File_anti_bruteforce_proto = out.File
	file_anti_bruteforce_proto_goTypes = nil
	file_anti_bruteforce_proto_depIdxs = nil
}
